/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __AppMsg_AppCmd_t_hpp__
#define __AppMsg_AppCmd_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

namespace AppMsg
{

class AppCmd_t
{
    public:
        int64_t    timestamp_us;

        std::string CmdName;

        int8_t     cmd_id;

        std::string cmd_data_type;

        int8_t     int_value;

        std::string string_value;

        float      SectionCleanPx1;

        float      SectionCleanPy1;

        float      SectionCleanPx2;

        float      SectionCleanPy2;

        float      SectionCleanPx3;

        float      SectionCleanPy3;

        float      SectionCleanPx4;

        float      SectionCleanPy4;

        float      SpotCleanPx1;

        float      SpotCleanPy1;

        float      RemoteCtrlWSpd;

        float      RemoteCtrlVSpd;

        int32_t    SpeechIndex;

        int32_t    Volume;

        int32_t    FanDuty;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "AppCmd_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int AppCmd_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AppCmd_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int AppCmd_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t AppCmd_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* AppCmd_t::getTypeName()
{
    return "AppCmd_t";
}

int AppCmd_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* CmdName_cstr = const_cast<char*>(this->CmdName.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &CmdName_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->cmd_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* cmd_data_type_cstr = const_cast<char*>(this->cmd_data_type.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &cmd_data_type_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->int_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* string_value_cstr = const_cast<char*>(this->string_value.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &string_value_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx2, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy2, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx3, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy3, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx4, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy4, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SpotCleanPx1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->SpotCleanPy1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->RemoteCtrlWSpd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->RemoteCtrlVSpd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->SpeechIndex, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Volume, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->FanDuty, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AppCmd_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __CmdName_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__CmdName_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__CmdName_len__ > maxlen - pos) return -1;
    this->CmdName.assign(
        static_cast<const char*>(buf) + offset + pos, __CmdName_len__ - 1);
    pos += __CmdName_len__;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->cmd_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __cmd_data_type_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__cmd_data_type_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__cmd_data_type_len__ > maxlen - pos) return -1;
    this->cmd_data_type.assign(
        static_cast<const char*>(buf) + offset + pos, __cmd_data_type_len__ - 1);
    pos += __cmd_data_type_len__;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->int_value, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __string_value_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__string_value_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__string_value_len__ > maxlen - pos) return -1;
    this->string_value.assign(
        static_cast<const char*>(buf) + offset + pos, __string_value_len__ - 1);
    pos += __string_value_len__;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx2, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy2, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx3, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy3, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPx4, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SectionCleanPy4, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SpotCleanPx1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->SpotCleanPy1, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->RemoteCtrlWSpd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->RemoteCtrlVSpd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->SpeechIndex, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Volume, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->FanDuty, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int AppCmd_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += this->CmdName.size() + 4 + 1;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += this->cmd_data_type.size() + 4 + 1;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += this->string_value.size() + 4 + 1;
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t AppCmd_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x47b2219d5a9a2821LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
