#ifndef EXCEPTIONHANDLERTASK_VERSION_H
#define EXCEPTIONHANDLERTASK_VERSION_H

#define EXCEPTIONHANDLERTASK_VERSION    "r44+43M 5df0bba"
#define EXCEPTIONHANDLERTASK_BUILD_TIME "2023-05-31_20:15:28"

#endif
