/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __TuyaMsg_TuyaXtPDO_t_hpp__
#define __TuyaMsg_TuyaXtPDO_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include <string>

namespace TuyaMsg
{

class TuyaXtPDO_t
{
    public:
        int64_t    timestamp_us;

        int32_t    seq;

        int32_t    keyNum;

        std::vector< int32_t > keyArray;

        int32_t    valueNum;

        std::vector< int32_t > valueArray;

        int32_t    virWallNum;

        std::vector< float > virWallPoses;

        int32_t    mopNum;

        std::vector< float > mopPoses;

        int32_t    bothNum;

        std::vector< float > bothPoses;

        int32_t    zoneNum;

        std::vector< float > zonePoses;

        int32_t    spotNum;

        std::vector< float > spotPoses;

        int32_t    roomSplitId;

        int32_t    roomSplitLineDataLen;

        std::vector< float > roomSplitLineData;

        int32_t    roomMergeIdNum;

        std::vector< int32_t > roomMergeIdArray;

        int8_t     roomReset;

        int32_t    roomPropertyNum;

        std::vector< int32_t > roomProperties;

        int32_t    roomNameNum;

        std::vector< int32_t > roomNameId;

        std::vector< std::string > roomNameArray;

        int32_t    roomCleanNum;

        std::vector< int32_t > roomCleanSeq;

        ///  Robot Cmd 
        int8_t     Rob_3dObsAvoidEnable;

        int32_t    Robo_ErrCode;

        int32_t    Rob_BackToCleanInternal;

        ///  Station Cmd 
        int32_t    Sta_Status;

        int32_t    Sta_WashMopMode;

        int8_t     Sta_AutoDustCollection;

        int32_t    Sta_AutoDustCollectionInternal;

        int8_t     Sta_AutoDry;

        int32_t    Sta_AutoWashWithPara;

        int8_t     Sta_AutoCarpetTurbo;

        int8_t     Sta_AutoFluid;

        int8_t     Sta_KeyLedOn;

        int8_t     Sta_ScreenLedOn;

        int8_t     Sta_KidLockOn;

        int32_t    Sta_Sn;

        int32_t    Sta_Version;

        int32_t    Sta_ErrCode;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "TuyaXtPDO_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int TuyaXtPDO_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int TuyaXtPDO_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int TuyaXtPDO_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t TuyaXtPDO_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* TuyaXtPDO_t::getTypeName()
{
    return "TuyaXtPDO_t";
}

int TuyaXtPDO_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->seq, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->keyNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->keyNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->keyArray[0], this->keyNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->valueNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->valueNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->valueArray[0], this->valueNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->virWallNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->virWallNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->virWallPoses[0], this->virWallNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->mopNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->mopNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->mopPoses[0], this->mopNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->bothNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->bothNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->bothPoses[0], this->bothNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->zoneNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->zoneNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->zonePoses[0], this->zoneNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->spotNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->spotNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->spotPoses[0], this->spotNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomSplitId, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomSplitLineDataLen, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomSplitLineDataLen > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->roomSplitLineData[0], this->roomSplitLineDataLen);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomMergeIdNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomMergeIdNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomMergeIdArray[0], this->roomMergeIdNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->roomReset, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomPropertyNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomPropertyNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomProperties[0], this->roomPropertyNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomNameNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomNameNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomNameId[0], this->roomNameNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->roomNameNum; a0++) {
        char* __cstr = const_cast<char*>(this->roomNameArray[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomCleanNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomCleanNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->roomCleanSeq[0], this->roomCleanNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Rob_3dObsAvoidEnable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Robo_ErrCode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Rob_BackToCleanInternal, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_Status, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_WashMopMode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDustCollection, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDustCollectionInternal, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDry, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoWashWithPara, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoCarpetTurbo, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoFluid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_KeyLedOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_ScreenLedOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_KidLockOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_Sn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_Version, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->Sta_ErrCode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int TuyaXtPDO_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->seq, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->keyNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->keyNum) {
        this->keyArray.resize(this->keyNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->keyArray[0], this->keyNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->valueNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->valueNum) {
        this->valueArray.resize(this->valueNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->valueArray[0], this->valueNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->virWallNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->virWallNum) {
        this->virWallPoses.resize(this->virWallNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->virWallPoses[0], this->virWallNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->mopNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->mopNum) {
        this->mopPoses.resize(this->mopNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->mopPoses[0], this->mopNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->bothNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->bothNum) {
        this->bothPoses.resize(this->bothNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->bothPoses[0], this->bothNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->zoneNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->zoneNum) {
        this->zonePoses.resize(this->zoneNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->zonePoses[0], this->zoneNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->spotNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->spotNum) {
        this->spotPoses.resize(this->spotNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->spotPoses[0], this->spotNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomSplitId, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomSplitLineDataLen, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomSplitLineDataLen) {
        this->roomSplitLineData.resize(this->roomSplitLineDataLen);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->roomSplitLineData[0], this->roomSplitLineDataLen);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomMergeIdNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomMergeIdNum) {
        this->roomMergeIdArray.resize(this->roomMergeIdNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomMergeIdArray[0], this->roomMergeIdNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->roomReset, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomPropertyNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomPropertyNum) {
        this->roomProperties.resize(this->roomPropertyNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomProperties[0], this->roomPropertyNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomNameNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomNameNum) {
        this->roomNameId.resize(this->roomNameNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomNameId[0], this->roomNameNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->roomNameArray.resize(this->roomNameNum);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->roomNameNum; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->roomNameArray[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomCleanNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->roomCleanNum) {
        this->roomCleanSeq.resize(this->roomCleanNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->roomCleanSeq[0], this->roomCleanNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Rob_3dObsAvoidEnable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Robo_ErrCode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Rob_BackToCleanInternal, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_Status, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_WashMopMode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDustCollection, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDustCollectionInternal, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoDry, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoWashWithPara, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoCarpetTurbo, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_AutoFluid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_KeyLedOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_ScreenLedOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_KidLockOn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_Sn, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_Version, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->Sta_ErrCode, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int TuyaXtPDO_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->keyNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->valueNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->virWallNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->mopNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->bothNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->zoneNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->spotNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->roomSplitLineDataLen);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->roomMergeIdNum);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->roomPropertyNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->roomNameNum);
    for (int a0 = 0; a0 < this->roomNameNum; a0++) {
        enc_size += this->roomNameArray[a0].size() + 4 + 1;
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->roomCleanNum);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t TuyaXtPDO_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xc453684d2fad7940LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
