#ifndef _PARSEMSG_H_
#define _PARSEMSG_H_

typedef enum
{
	REQUEST_MAP =           99,
	REQUEST_LASER =         2,
	REQUEST_AMCLODOM =      3,
	REQUEST_AMCLPARTICLES = 4,
	REQUEST_NEXTLINE =      5,
	REQUEST_ZPLANLINES =    6,
	REQUEST_ODOM =          7,
	REQUEST_GMODOM =        8,
	REQUEST_DSTARMAP =      9,
	REQUEST_GLOBALCOSTMAP = 10,
	REQUEST_LOCALCOSTMAP =  11,
	REQUEST_GLOBALPATH =    12,
	REQUEST_LOCALPATH =     13,
	REQUEST_PREDPATH =      14,
	REQUEST_DISTRICTSHAPE = 15,
	REQUEST_LASERX1Q =      16,
	REQUEST_FASTSLAM =      17,
	REQUEST_MAPEXP3DOBSMARKER = 18,
	REQUEST_TRAJECTORYPATH = 19,
	REQUEST_ODOMTRAJECTORYPATH = 20,
	REQUEST_GMODOMTRAJECTORYPATH = 21,
	REQUEST_PARTICLECLOED = 22,
	REQUEST_GMAPGCLOUD    = 23,
	REQUEST_LASERX1C      = 24,
	REQUEST_ODOMNEXTLINE  = 25,
	REQUEST_DYNAMICMAP    = 26,


	REQUEST_OBSMAP =        100,
	REQUEST_CLEANEDMAP =    101,
	REQUEST_OBSCLEANEDMAP = 102
}monitor_request_t;


#endif