/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __CostMap2DMsg_PointCloud_t_hpp__
#define __CostMap2DMsg_PointCloud_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include <vector>

namespace CostMap2DMsg
{

class PointCloud_t
{
    public:
        std::string name;

        int64_t    timestamp_us;

        int32_t    PointNum;

        int32_t    width;

        int32_t    height;

        std::vector< float > x;

        std::vector< float > y;

        std::vector< float > z;
        
        PointCloud_t(const PointCloud_t &cloud)
        {
            name = cloud.name;
            timestamp_us = cloud.timestamp_us;
            PointNum = cloud.PointNum;
            width = cloud.width;
            height = cloud.height;
            x = cloud.x;
            y = cloud.y;
            z = cloud.z;


        };
        PointCloud_t()
        {
            name.clear();
            timestamp_us = 0;
            PointNum = 0;
            width = 0;
            height = 0;
            x.clear();
            y.clear();
            z.clear();
        };

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "PointCloud_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int PointCloud_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int PointCloud_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PointCloud_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t PointCloud_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* PointCloud_t::getTypeName()
{
    return "PointCloud_t";
}

int PointCloud_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* name_cstr = const_cast<char*>(this->name.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->PointNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->PointNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->x[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->PointNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->y[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->PointNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->z[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int PointCloud_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __name_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__name_len__ > maxlen - pos) return -1;
    this->name.assign(
        static_cast<const char*>(buf) + offset + pos, __name_len__ - 1);
    pos += __name_len__;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp_us, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->PointNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->PointNum) {
        this->x.resize(this->PointNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->x[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->PointNum) {
        this->y.resize(this->PointNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->y[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->PointNum) {
        this->z.resize(this->PointNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->z[0], this->PointNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int PointCloud_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->name.size() + 4 + 1;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->PointNum);
    enc_size += __float_encoded_array_size(NULL, this->PointNum);
    enc_size += __float_encoded_array_size(NULL, this->PointNum);
    return enc_size;
}

uint64_t PointCloud_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x0ca89c2df33afb9dLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
