// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "TuyaMsg_TaskFinishStatus_t.h"

static int __TuyaMsg_TaskFinishStatus_t_hash_computed;
static uint64_t __TuyaMsg_TaskFinishStatus_t_hash;

uint64_t __TuyaMsg_TaskFinishStatus_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __TuyaMsg_TaskFinishStatus_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __TuyaMsg_TaskFinishStatus_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xcaad8d30cac21ed3LL
         + __int64_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __TuyaMsg_TaskFinishStatus_t_get_hash(void)
{
    if (!__TuyaMsg_TaskFinishStatus_t_hash_computed) {
        __TuyaMsg_TaskFinishStatus_t_hash = (int64_t)__TuyaMsg_TaskFinishStatus_t_hash_recursive(NULL);
        __TuyaMsg_TaskFinishStatus_t_hash_computed = 1;
    }

    return __TuyaMsg_TaskFinishStatus_t_hash;
}

int __TuyaMsg_TaskFinishStatus_t_encode_array(void *buf, int offset, int maxlen, const TuyaMsg_TaskFinishStatus_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_us), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].saveMap), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int TuyaMsg_TaskFinishStatus_t_encode(void *buf, int offset, int maxlen, const TuyaMsg_TaskFinishStatus_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __TuyaMsg_TaskFinishStatus_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __TuyaMsg_TaskFinishStatus_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __TuyaMsg_TaskFinishStatus_t_encoded_array_size(const TuyaMsg_TaskFinishStatus_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp_us), 1);

        size += __boolean_encoded_array_size(&(p[element].saveMap), 1);

    }
    return size;
}

int TuyaMsg_TaskFinishStatus_t_encoded_size(const TuyaMsg_TaskFinishStatus_t *p)
{
    return 8 + __TuyaMsg_TaskFinishStatus_t_encoded_array_size(p, 1);
}

int __TuyaMsg_TaskFinishStatus_t_decode_array(const void *buf, int offset, int maxlen, TuyaMsg_TaskFinishStatus_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_us), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].saveMap), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __TuyaMsg_TaskFinishStatus_t_decode_array_cleanup(TuyaMsg_TaskFinishStatus_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp_us), 1);

        __boolean_decode_array_cleanup(&(p[element].saveMap), 1);

    }
    return 0;
}

int TuyaMsg_TaskFinishStatus_t_decode(const void *buf, int offset, int maxlen, TuyaMsg_TaskFinishStatus_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __TuyaMsg_TaskFinishStatus_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __TuyaMsg_TaskFinishStatus_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int TuyaMsg_TaskFinishStatus_t_decode_cleanup(TuyaMsg_TaskFinishStatus_t *p)
{
    return __TuyaMsg_TaskFinishStatus_t_decode_array_cleanup(p, 1);
}

int __TuyaMsg_TaskFinishStatus_t_clone_array(const TuyaMsg_TaskFinishStatus_t *p, TuyaMsg_TaskFinishStatus_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp_us), &(q[element].timestamp_us), 1);

        __boolean_clone_array(&(p[element].saveMap), &(q[element].saveMap), 1);

    }
    return 0;
}

TuyaMsg_TaskFinishStatus_t *TuyaMsg_TaskFinishStatus_t_copy(const TuyaMsg_TaskFinishStatus_t *p)
{
    TuyaMsg_TaskFinishStatus_t *q = (TuyaMsg_TaskFinishStatus_t*) malloc(sizeof(TuyaMsg_TaskFinishStatus_t));
    __TuyaMsg_TaskFinishStatus_t_clone_array(p, q, 1);
    return q;
}

void TuyaMsg_TaskFinishStatus_t_destroy(TuyaMsg_TaskFinishStatus_t *p)
{
    __TuyaMsg_TaskFinishStatus_t_decode_array_cleanup(p, 1);
    free(p);
}

int TuyaMsg_TaskFinishStatus_t_publish(lcm_t *lc, const char *channel, const TuyaMsg_TaskFinishStatus_t *p)
{
      int max_data_size = TuyaMsg_TaskFinishStatus_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = TuyaMsg_TaskFinishStatus_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _TuyaMsg_TaskFinishStatus_t_subscription_t {
    TuyaMsg_TaskFinishStatus_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void TuyaMsg_TaskFinishStatus_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    TuyaMsg_TaskFinishStatus_t p;
    memset(&p, 0, sizeof(TuyaMsg_TaskFinishStatus_t));
    status = TuyaMsg_TaskFinishStatus_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding TuyaMsg_TaskFinishStatus_t!!!\n", status);
        return;
    }

    TuyaMsg_TaskFinishStatus_t_subscription_t *h = (TuyaMsg_TaskFinishStatus_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    TuyaMsg_TaskFinishStatus_t_decode_cleanup (&p);
}

TuyaMsg_TaskFinishStatus_t_subscription_t* TuyaMsg_TaskFinishStatus_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    TuyaMsg_TaskFinishStatus_t_handler_t f, void *userdata)
{
    TuyaMsg_TaskFinishStatus_t_subscription_t *n = (TuyaMsg_TaskFinishStatus_t_subscription_t*)
                       malloc(sizeof(TuyaMsg_TaskFinishStatus_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 TuyaMsg_TaskFinishStatus_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg TuyaMsg_TaskFinishStatus_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int TuyaMsg_TaskFinishStatus_t_subscription_set_queue_capacity (TuyaMsg_TaskFinishStatus_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int TuyaMsg_TaskFinishStatus_t_unsubscribe(lcm_t *lcm, TuyaMsg_TaskFinishStatus_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe TuyaMsg_TaskFinishStatus_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

