/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __NavMsg_Polygon_t_hpp__
#define __NavMsg_Polygon_t_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "Pose_t.hpp"
#include "Point_t.hpp"
#include "Point_t.hpp"
#include "Pose_t.hpp"

namespace NavMsg
{

class Polygon_t
{
    public:
        int32_t    id;

        float      zPa;

        NavMsg::Pose_t wallPose;

        int8_t     isCleaned;

        int8_t     isRecognized;

        int32_t    pointNum;

        std::vector< NavMsg::Point_t > points;

        int32_t    pointRawNum;

        std::vector< NavMsg::Point_t > pointsRaw;

        int32_t    entryNum;

        std::vector< int32_t > nextBlkIdOfEntries;

        std::vector< NavMsg::Pose_t > entryPoses;

        int32_t    forbiddenBothNum;

        std::vector< float > forbiddenBothZones;

        int32_t    forbiddenMopNum;

        std::vector< float > forbiddenMopZones;

        int32_t    virwallNum;

        std::vector< float > virwallZones;

        int32_t    cleanOrder;

        int32_t    cleanTime;

        int32_t    mopTime;

        int8_t     mopForbidden;

        int8_t     cleanForbidden;

        int32_t    fanRank;

        int32_t    waterBoxRank;

        int32_t    yModeEnable;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "Polygon_t"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int Polygon_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Polygon_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Polygon_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t Polygon_t::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* Polygon_t::getTypeName()
{
    return "Polygon_t";
}

int Polygon_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->zPa, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->wallPose._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->isCleaned, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->isRecognized, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->pointNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->pointNum; a0++) {
        tlen = this->points[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->pointRawNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->pointRawNum; a0++) {
        tlen = this->pointsRaw[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->entryNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->entryNum > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nextBlkIdOfEntries[0], this->entryNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->entryNum; a0++) {
        tlen = this->entryPoses[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->forbiddenBothNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->forbiddenBothNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->forbiddenBothZones[0], this->forbiddenBothNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->forbiddenMopNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->forbiddenMopNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->forbiddenMopZones[0], this->forbiddenMopNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->virwallNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->virwallNum > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->virwallZones[0], this->virwallNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->cleanOrder, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->cleanTime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->mopTime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->mopForbidden, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->cleanForbidden, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->fanRank, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->waterBoxRank, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->yModeEnable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Polygon_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->zPa, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->wallPose._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->isCleaned, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->isRecognized, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->pointNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->points.resize(this->pointNum);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->pointNum; a0++) {
        tlen = this->points[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->pointRawNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->pointsRaw.resize(this->pointRawNum);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->pointRawNum; a0++) {
        tlen = this->pointsRaw[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->entryNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->entryNum) {
        this->nextBlkIdOfEntries.resize(this->entryNum);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nextBlkIdOfEntries[0], this->entryNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->entryPoses.resize(this->entryNum);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->entryNum; a0++) {
        tlen = this->entryPoses[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->forbiddenBothNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->forbiddenBothNum) {
        this->forbiddenBothZones.resize(this->forbiddenBothNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->forbiddenBothZones[0], this->forbiddenBothNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->forbiddenMopNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->forbiddenMopNum) {
        this->forbiddenMopZones.resize(this->forbiddenMopNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->forbiddenMopZones[0], this->forbiddenMopNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->virwallNum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->virwallNum) {
        this->virwallZones.resize(this->virwallNum);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->virwallZones[0], this->virwallNum);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->cleanOrder, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->cleanTime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->mopTime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->mopForbidden, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->cleanForbidden, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->fanRank, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->waterBoxRank, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->yModeEnable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Polygon_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += this->wallPose._getEncodedSizeNoHash();
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->pointNum; a0++) {
        enc_size += this->points[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->pointRawNum; a0++) {
        enc_size += this->pointsRaw[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->entryNum);
    for (int a0 = 0; a0 < this->entryNum; a0++) {
        enc_size += this->entryPoses[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->forbiddenBothNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->forbiddenMopNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->virwallNum);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t Polygon_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == Polygon_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, Polygon_t::getHash };

    uint64_t hash = 0xaf61a1a43e39283bLL +
         NavMsg::Pose_t::_computeHash(&cp) +
         NavMsg::Point_t::_computeHash(&cp) +
         NavMsg::Point_t::_computeHash(&cp) +
         NavMsg::Pose_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
